mybatis:
  type-handlers-package: com.test.kms.AESStringTypeHandler

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**
  #DB 설정
  datasource:
    #    url: jdbc:postgresql://127.0.0.1:5432/test_02
    #   writer
#    url: jdbc-secretsmanager:postgresql://awsdc-rds-flt-dev-oc-pri.ceowunjax3dw.ap-northeast-2.rds.amazonaws.com:5957/ocdevdb
    #   reader
    url: jdbc-secretsmanager:postgresql://ke-test-db-dev.cluster-ro-cwt0xlqwsn2i.ap-northeast-2.rds.amazonaws.com/ke_dev
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    username: arn:aws:secretsmanager:ap-northeast-2:273563728071:secret:prod/AppDev/Postgresql-PEu1We
    password: arn:aws:secretsmanager:ap-northeast-2:273563728071:secret:prod/AppDev/Postgresql-PEu1We
  #JSP 바로적용 설정
  devtools:
    livereload:
      enabled: true

aws:
  secretsmanager:
    name: prod/AppDev/Postgresql
  kms:
    keyId: "8dce5d89-41df-4ac5-8894-5f8c758ca821"
    encryptionAlgorithm: "RSAES_OAEP_SHA_256"
cloud:
  aws:
    region:
      static: ap-northeast-2